repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check .
        language: system
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: ruff format --check .
        language: system
        types: [python]
